### ISSUE TITLE
alpine-linux-musl build can not link

### ISSUE THREAD

**Issue by coyzeng** [kuzudb/go-kuzu#33]
```shell
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
139.5 /usr/bin/gcc -m64 -s -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=crosscall2 -Wl,--compress-debug-sections=zlib /tmp/go-link-2039681432/go.o /tmp/go-link-2039681432/000000.o /tmp/go-link-2039681432/000001.o /tmp/go-link-2039681432/000002.o /tmp/go-link-2039681432/000003.o /tmp/go-link-2039681432/000004.o /tmp/go-link-2039681432/000005.o /tmp/go-link-2039681432/000006.o /tmp/go-link-2039681432/000007.o /tmp/go-link-2039681432/000008.o /tmp/go-link-2039681432/000009.o /tmp/go-link-2039681432/000010.o /tmp/go-link-2039681432/000011.o /tmp/go-link-2039681432/000012.o /tmp/go-link-2039681432/000013.o /tmp/go-link-2039681432/000014.o /tmp/go-link-2039681432/000015.o /tmp/go-link-2039681432/000016.o /tmp/go-link-2039681432/000017.o /tmp/go-link-2039681432/000018.o /tmp/go-link-2039681432/000019.o /tmp/go-link-2039681432/000020.o /tmp/go-link-2039681432/000021.o /tmp/go-link-2039681432/000022.o /tmp/go-link-2039681432/000023.o /tmp/go-link-2039681432/000024.o /tmp/go-link-2039681432/000025.o /tmp/go-link-2039681432/000026.o /tmp/go-link-2039681432/000027.o /tmp/go-link-2039681432/000028.o /tmp/go-link-2039681432/000029.o /tmp/go-link-2039681432/000030.o /tmp/go-link-2039681432/000031.o -O2 -g -lresolv -O2 -g -O2 -g -lpthread -O2 -g -L/go/pkg/mod/github.com/kuzudb/go-kuzu@v0.7.0/lib/dynamic/linux-amd64 -lkuzu -Wl,-rpath,/go/pkg/mod/github.com/kuzudb/go-kuzu@v0.7.0/lib/dynamic/linux-amd64 -no-pie -static
139.5 /usr/lib/gcc/x86_64-alpine-linux-musl/14.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lkuzu: No such file or directory
139.5 collect2: error: ld returned 1 exit status
```

**Comment by coyzeng** [comment]
And I want to become the project contributor.

**Comment by mewim** [comment]
> ```shell
> /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
> 139.5 /usr/bin/gcc -m64 -s -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=crosscall2 -Wl,--compress-debug-sections=zlib /tmp/go-link-2039681432/go.o /tmp/go-link-2039681432/000000.o /tmp/go-link-2039681432/000001.o /tmp/go-link-2039681432/000002.o /tmp/go-link-2039681432/000003.o /tmp/go-link-2039681432/000004.o /tmp/go-link-2039681432/000005.o /tmp/go-link-2039681432/000006.o /tmp/go-link-2039681432/000007.o /tmp/go-link-2039681432/000008.o /tmp/go-link-2039681432/000009.o /tmp/go-link-2039681432/000010.o /tmp/go-link-2039681432/000011.o /tmp/go-link-2039681432/000012.o /tmp/go-link-2039681432/000013.o /tmp/go-link-2039681432/000014.o /tmp/go-link-2039681432/000015.o /tmp/go-link-2039681432/000016.o /tmp/go-link-2039681432/000017.o /tmp/go-link-2039681432/000018.o /tmp/go-link-2039681432/000019.o /tmp/go-link-2039681432/000020.o /tmp/go-link-2039681432/000021.o /tmp/go-link-2039681432/000022.o /tmp/go-link-2039681432/000023.o /tmp/go-link-2039681432/000024.o /tmp/go-link-2039681432/000025.o /tmp/go-link-2039681432/000026.o /tmp/go-link-2039681432/000027.o /tmp/go-link-2039681432/000028.o /tmp/go-link-2039681432/000029.o /tmp/go-link-2039681432/000030.o /tmp/go-link-2039681432/000031.o -O2 -g -lresolv -O2 -g -O2 -g -lpthread -O2 -g -L/go/pkg/mod/github.com/kuzudb/go-kuzu@v0.7.0/lib/dynamic/linux-amd64 -lkuzu -Wl,-rpath,/go/pkg/mod/github.com/kuzudb/go-kuzu@v0.7.0/lib/dynamic/linux-amd64 -no-pie -static
> 139.5 /usr/lib/gcc/x86_64-alpine-linux-musl/14.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lkuzu: No such file or directory
> 139.5 collect2: error: ld returned 1 exit status
> ```

Hi @coyzeng, 

Currently we do not provide pre-compiled binaries linking to musl libc that works on Alpine Linux. Our pre-compiled binaries are built against glibc. If you'd like to use kuzu on Alpine Linux or other musl libc based distros, you can compile kuzu by yourself on that platform, replace `libkuzu` binary under `lib/dynamic` and it should work. However, we do not recommend running kuzu on Alpine unless you have very specific requirements. If you are using kuzu on Docker, we recommend using Debian / Ubuntu / Fedora as the base image.

**Comment by mewim** [comment]
> And I want to become the project contributor.

We welcome contributions. Feel free to fork the repository, make changes and open PR to our repos. Please read our [contributing guideline](https://github.com/kuzudb/kuzu/blob/master/CONTRIBUTING.md). If you have specific question / proposal / things to discuss, we encourage you to join our [Discord](https://discord.gg/VtX2gw9Rug) to chat with us.
